# Generated by Django 4.0.4 on 2022-05-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsBestQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerinfo', models.CharField(db_column='BuyerInfo', max_length=125)),
                ('amazonorderid', models.CharField(db_column='AmazonOrderId', max_length=19)),
                ('asin', models.CharField(db_column='ASIN', max_length=10)),
                ('orderitemid', models.CharField(db_column='OrderItemId', max_length=14)),
                ('sellersku', models.CharField(db_column='SellerSKU', max_length=50)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('quantityordered', models.IntegerField(db_column='QuantityOrdered')),
                ('quantityshipped', models.IntegerField(db_column='QuantityShipped')),
                ('productinfo', models.CharField(db_column='ProductInfo', max_length=22)),
                ('itemprice', models.TextField(db_column='ItemPrice')),
                ('shippingprice', models.CharField(blank=True, db_column='ShippingPrice', max_length=55, null=True)),
                ('itemtax', models.CharField(db_column='ItemTax', max_length=55)),
                ('shippingtax', models.CharField(blank=True, db_column='ShippingTax', max_length=55, null=True)),
                ('shippingdiscount', models.CharField(blank=True, db_column='ShippingDiscount', max_length=55, null=True)),
                ('shippingdiscounttax', models.CharField(blank=True, db_column='ShippingDiscountTax', max_length=55, null=True)),
                ('promotiondiscount', models.CharField(db_column='PromotionDiscount', max_length=55)),
                ('promotiondiscounttax', models.CharField(db_column='PromotionDiscountTax', max_length=55)),
                ('promotionids', models.CharField(blank=True, db_column='PromotionIds', max_length=65, null=True)),
                ('isgift', models.CharField(db_column='IsGift', max_length=5)),
                ('pricedesignation', models.CharField(blank=True, db_column='PriceDesignation', max_length=55, null=True)),
                ('conditionid', models.CharField(blank=True, db_column='ConditionId', max_length=25, null=True)),
                ('conditionsubtypeid', models.CharField(blank=True, db_column='ConditionSubtypeId', max_length=25, null=True)),
                ('istransparency', models.IntegerField(db_column='IsTransparency')),
                ('deemedresellercategory', models.CharField(blank=True, db_column='DeemedResellerCategory', max_length=5, null=True)),
                ('purchasedate', models.DateTimeField(db_column='PurchaseDate')),
                ('iossnumber', models.CharField(blank=True, db_column='IossNumber', max_length=12, null=True)),
            ],
            options={
                'db_table': '2022___bestq___es___items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadsBestQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazonorderid', models.CharField(db_column='AmazonOrderId', max_length=19)),
                ('x_amz_security_token', models.CharField(db_column='X-Amz-Security-Token', max_length=1200)),
                ('x_amz_algorithm', models.CharField(db_column='X-Amz-Algorithm', max_length=16)),
                ('x_amz_date', models.CharField(db_column='X-Amz-Date', max_length=16)),
                ('x_amz_signedheaders', models.CharField(db_column='X-Amz-SignedHeaders', max_length=50)),
                ('x_amz_expires', models.IntegerField(db_column='X-Amz-Expires')),
                ('x_amz_credential', models.CharField(db_column='X-Amz-Credential', max_length=65)),
                ('x_amz_signature', models.CharField(db_column='X-Amz-Signature', max_length=65)),
                ('submissiondate', models.DateTimeField(db_column='submissionDate')),
                ('method', models.CharField(max_length=5)),
                ('file', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('x_amz_server_side_encryption', models.CharField(db_column='x-amz-server-side-encryption', max_length=7)),
                ('content_md5', models.CharField(db_column='Content-MD5', max_length=50)),
                ('uploaddestinationid', models.CharField(db_column='uploadDestinationId', max_length=36)),
            ],
            options={
                'db_table': 'bestq___es___uploads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
    ]
