# Generated by Django 4.0.4 on 2022-05-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orders_uploads_delete_itemsbestq_delete_uploadsbestq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
    ]
